services:

  r:
    build: ./setup/r
    image: lipovseklab/tiny-plotter-r
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=plot
    volumes:
      - ./workspace:/home/rstudio/workspace

  python:
    build: ./setup/python
    image: lipovseklab/tiny-plotter-python
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=plot
      - GRANT_SUDO=yes
    volumes:
      - ./workspace:/home/jovyan/workspace
